### ISSUE TITLE
HVACMode(s) not fully implemented

### ISSUE THREAD

**Issue by xvb201** [pwesters/watts_vision#21] opened 2024-12-04 06:37 UTC
In the log the following line can be found. Running Home Assistant Core 2024.11.2, and Watts Vision 0.4.4

2024-12-04 07:20:31.832 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.watts_vision.climate.WattsThermostat'>) implements HVACMode(s): heat, cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/pwesters/watts_vision/issues

**Comment by pwesters** [comment] 2024-12-06 08:56
Duplicate of #17

**Closed** 2024-12-15 11:48 UTC
